Add Plastik token
valora-inc/address-metadata pull request #28
Opened 2022-08-16 10:19 UTC by garciapd

Add Plastik token!

2022-08-16 18:35 UTC, MuckT requested changes
The addresses look good in explorer, they just need to be lower cased.

2022-08-16 18:35 UTC, MuckT commented on src/data/alfajores/tokens-info.json
> +    "address": "0x55067df868997BaD76e831F4bad5B48fbbf4c8D1",
Please lower-case this address.

2022-08-16 18:35 UTC, MuckT commented on src/data/mainnet/tokens-info.json
> +    "address": "0xf4361a8Fbcf6b6A2402f1A1d6c4b945e59a29934",
Please lower-case this address.

2022-08-16 18:48 UTC, garciapd commented on src/data/alfajores/tokens-info.json
> +    "address": "0x55067df868997BaD76e831F4bad5B48fbbf4c8D1",
done!

2022-08-16 18:49 UTC, garciapd commented on src/data/mainnet/tokens-info.json
> +    "address": "0xf4361a8Fbcf6b6A2402f1A1d6c4b945e59a29934",
done!

2022-08-16 18:49 UTC, garciapd commented
@MuckT could you please review?

2022-08-16 19:05 UTC, MuckT approved these changes
[PKS Test Token](https://alfajores-blockscout.celo-testnet.org/token/0x55067df868997BaD76e831F4bad5B48fbbf4c8D1/token-transfers)
[PLASTIK Token (PLASTIK)](https://explorer.celo.org/address/0xf4361a8Fbcf6b6A2402f1A1d6c4b945e59a29934/logs)

2022-08-17 16:44 UTC, merged

2022-08-17 18:19 UTC, garciapd commented
@MuckT is 0x55067df868997BaD76e831F4bad5B48fbbf4c8D1

yes