Adding cCOP token
valora-inc/address-metadata pull request #580
Opened 2024-10-31 17:25 UTC by celoorgcolombia

2024-10-31 17:42 UTC, MuckT requested changes

2024-10-31 17:42 UTC, MuckT commented on src/data/mainnet/celo-tokens-info.json
> +    "address": "0x8A567e2aE79CA692Bd748aB832081C45de4041eA",
```suggestion
    "address": "0x8a567e2ae79ca692bd748ab832081c45de4041ea",
```

2024-10-31 17:42 UTC, MuckT commented on src/data/mainnet/celo-tokens-info.json
> +    "minimumAppVersionToSwap": "1.68.0",
```suggestion
```

2024-11-01 18:22 UTC, celoorgcolombia commented
@MuckT we already included the changes you requested. Can you please check again?

2024-11-02 19:37 UTC, MuckT approved these changes

2024-11-02 19:37 UTC, merged

2024-11-03 16:15 UTC, celoorgcolombia commented
@MuckT Thanks for merging PR but now how we can add the price feed to be tracked?
Chainlik Data Feed https://data.chain.link/feeds/celo/mainnet/cop-usd#operator-chainlayer